const PORT = 3000
const AWS_ACCESS_ID  = "ACCESS_KEY_OF_IAM_USER_WITH_STORAGE_ACCESS"
const AWS_ACCESS_TOKEN = "ACCESS_TOKEN_OF_IAM_USER_WITH_STORAGE_ACCESS"
module.exports = {PORT,AWS_ACCESS_ID,AWS_ACCESS_TOKEN}
